### ISSUE TITLE
Bug: Globs work in my machine but fails on CI

### ISSUE THREAD

**Issue by rhuanbarreto** [python-jsonschema/check-jsonschema#374]
When I run the command on my Mac it works properly, but on Github actions, it fails.
```
Run check-jsonschema --schemafile infra/deploy.yaml.schema.json src/**/deploy.yaml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.6/x64/bin/check-jsonschema", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 2356, in process_value
    value = self.type_cast_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 2344, in type_cast_value
    return convert(value)
           ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 2321, in convert
    return tuple(self.type(x, self, ctx) for x in check_iter(value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/core.py", line 2321, in <genexpr>
    return tuple(self.type(x, self, ctx) for x in check_iter(value))
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/click/types.py", line 83, in __call__
    return self.convert(value, param, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/check_jsonschema/cli/param_types.py", line 153, in convert
    lf = CustomLazyFile(value_, mode="rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/check_jsonschema/cli/param_types.py", line 132, in __init__
    if "r" in mode and not stat.S_ISFIFO(os.stat(filename).st_mode):
                                         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src/**/deploy.yaml'
```

**Comment by sirosen** [comment]
I don't think this is a bug in check-jsonschema.

It looks like you're using an extended glob expression and the shell in GitHub Actions doesn't have extended globbing enabled. So the literal expression gets passed. It's not the command's responsibility to expand that.

Probably it's a bash shell and you need to `shopt -s extglob`.

It also looks like I could clean up the output for running on nonexistent files.

**Comment by rhuanbarreto** [comment]
Thanks for the help! Indeed, `zsh` have glob expansion. I had to use `shopt -s globstar` for fixing in bash.
Maybe this could be a feature added to the CLI then? Support glob expansion on the files so we don't need to enable this in bash?

**Comment by sirosen** [comment]
No, glob expansion is the responsibility of the calling shell, not the tool being invoked. There would be many problems adding it, e.g. losing the ability to support filenames with literal `*` characters.

In any case, I'm glad that turning on extglob got things working for you!
