### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ssbarnea** [python-jsonschema/check-jsonschema#89]
If the instance to be validated contains something like below, it would throw an exception.

```
$ cat negative_test/playbooks/vars/numeric-var-name.yml 
---
12: ... # invalid var name
```

# Exception

```
$ python -m check_jsonschema --schemafile f/ansible-vars.json negative_test/playbooks/vars/numeric-var-name.yml
Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/check_jsonschema/__main__.py", line 3, in <module>
    main()
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/check_jsonschema/__init__.py", line 26, in main
    ret = checker.run()
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/check_jsonschema/checker.py", line 88, in run
    self._run()
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/check_jsonschema/checker.py", line 71, in _run
    errors = self._build_error_map()
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/check_jsonschema/checker.py", line 63, in _build_error_map
    for err in validator.iter_errors(doc):
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jsonschema/validators.py", line 229, in iter_errors
    for error in errors:
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jsonschema/_validators.py", line 368, in anyOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jsonschema/validators.py", line 245, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jsonschema/validators.py", line 229, in iter_errors
    for error in errors:
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jsonschema/_validators.py", line 42, in additionalProperties
    extras = set(find_additional_properties(instance, schema))
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jsonschema/_utils.py", line 101, in find_additional_properties
    if patterns and re.search(patterns, property):
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by ssbarnea** [comment]
Feel free to transfer this bug to jsonschema project as I do not have permissions to transfer.

**Comment by sirosen** [comment]
I can wait to see a response on python-jsonschema/jsonschema#944 , but I think this is really a bug for `check-jsonschema` to resolve.

JSON data does not support non-string keys. We should make all loaded data conform to that same condition by stringifying the keys in all cases. I'll hopefully be able to address this in the next couple of days.

**Comment by ssbarnea** [comment]
@sirosen You are right, as JSON does not allow non-string keys, there is nothing that jsonschema library can do about it. Basically we would have to jsonify the the yaml object before using with with the schema. Once change is obvious now would be conversion of all keys to strings but we might need other bits in the future.

**Comment by sirosen** [comment]
Fixed in https://github.com/python-jsonschema/check-jsonschema/commit/8fe6badbec96726c42ddcac43f1d769c4193fbc6

**Comment by ssbarnea** [comment]
@sirosen Thanks! Any chance you could make a new release with that patch?

**Comment by ssbarnea** [comment]
@sirosen Do you happen to be on json-schema slack instance `#tests` channel? I sent you an invite. Cheers, Sorin!

**Comment by sirosen** [comment]
I've just released v0.15.0 with this and many other changes. Please let me know if you see issues using it!

Regarding json-schema Slack... I may join at some point, but not today. For my own ability to manage my responsibilities -- work and otherwise -- I much prefer async communication mechanisms. I have some bad habits regarding IM platforms, tending to treat all direct messages as urgent and interrupting whatever I'm doing to read and reply. I'm always reachable for project-specific issues via GitHub issues or over email for anything less specific.
